
syntax = "proto3";

package Msg;

option csharp_namespace = "Msg";
option go_package = "msg";


enum MsgType {
	TheFragmentInfo = 0;
	TheCopyInfo = 1;
	TheCrystalInfo = 2;
	TheRoleSkillInfo = 3;
	TheTalentSkillInfo = 4;
	TheEventCopyInfo = 5;
	TheLimitTaskInfo = 6;
	TheShopGoods = 7;
	TheHeroMission = 8;
	TheHeroGoods = 9;
	TheAchievementInfo = 10;
	TheHeroInfo = 11;
	TheMailInfo = 12;
	TheMailList = 13;
	TheFriendInfo = 14;
	TheFriendDetailInfo = 15;
	TheFriendRequest = 16;
	ThePVPBattleRecord = 17;
	ThePVPBattleRecordDetail = 18;
	ThePVPOpponentPlayer = 19;
	TheLoginAwardInfo = 20;
	TheFormationInfo = 21;
	TheFormationList = 22;
	ThePlayerInfo = 23;
	TheMonsterInfo = 24;
	TheNormalLoot = 25;
	TheLootObject = 26;
	TheLootObjectList = 27;
	TheGameConfig = 28;
	ThePVPOpponentInfo = 29;
	TheClassesExchangeInfo = 30;
	TheOtherPlayerInfo = 31;
	TheIapInfo = 32;
	ThePing = 33;
	ThePong = 34;
	TheKeepLive = 35;
	TheServerInfoR = 36;
	TheServerInfoA = 37;
	TheVersionCheckR = 38;
	TheVersionCheckA = 39;
	TheRookieAwardInfo = 40;
	TheRookieLoginAwardInfo = 41;
	TheRookieQuestInfo = 42;
	TheWheelObjectInfo = 43;
	TheLuckyShopGoods = 44;
	TheVerConfigR = 45;
	TheVerConfigA = 46;
	TheTableR = 47;
	TheTableA = 48;
	TheDeviceLoginR = 49;
	TheDeviceLoginA = 50;
	TheOtherLogin = 51;
	ThePlayerLoginR = 52;
	ThePlayerLoginA = 53;
	TheGetHeroListR = 54;
	TheGetHeroListA = 55;
	TheGetPlayerDataR = 56;
	TheGetPlayerDataA = 57;
	TheSummonHeroR = 58;
	TheSummonHeroA = 59;
	TheUseFragmentR = 60;
	TheUseFragmentA = 61;
	TheHeroUpgradeR = 62;
	TheHeroUpgradeA = 63;
	TheChangeFormationR = 64;
	TheChangeFormationA = 65;
	TheSellEquipR = 66;
	TheSellEquipA = 67;
	TheComposeEquipR = 68;
	TheComposeEquipA = 69;
	ThePutOnEquipR = 70;
	ThePutOnEquipA = 71;
	TheTakeOffEquipR = 72;
	TheTakeOffEquipA = 73;
	TheSyncNormalLoot = 74;
	TheSyncCopyProgress = 75;
	TheNotifyRandomLoot = 76;
	TheCopyBossPassR = 77;
	TheCopyBossPassA = 78;
	TheGainOfflineAwardR = 79;
	TheGainOfflineAwardA = 80;
	ThePutOnRoleSkillR = 81;
	ThePutOnRoleSkillA = 82;
	TheRoleSkillUnlockR = 83;
	TheRoleSkillUnlockA = 84;
	TheRoleSkillLevelUpR = 85;
	TheRoleSkillLevelUpA = 86;
	TheRoleSkillQualityUpR = 87;
	TheRoleSkillQualityUpA = 88;
	TheUnlockCrystalR = 89;
	TheUnlockCrystalA = 90;
	TheUpgradeCrystalR = 91;
	TheUpgradeCrystalA = 92;
	TheConvertCrystalR = 93;
	TheConvertCrystalA = 94;
	TheSaveConvertCrystalR = 95;
	TheSaveConvertCrystalA = 96;
	TheHeroDecomposeR = 97;
	TheHeroDecomposeA = 98;
	TheHeroIDs = 99;
	TheHeroStarUpR = 100;
	TheHeroStarUpA = 101;
	TheHeroTierUpR = 102;
	TheHeroTierUpA = 103;
	TheRoleTitleUpR = 104;
	TheRoleTitleUpA = 105;
	TheNotifySummonActivityReset = 106;
	TheGetDailyAdAwardR = 107;
	TheGetDailyAdAwardA = 108;
	TheSaveHeroTalentR = 109;
	TheSaveHeroTalentA = 110;
	TheActiveRoleTalentR = 111;
	TheActiveRoleTalentA = 112;
	TheStartEventCopyR = 113;
	TheStartEventCopyA = 114;
	ThePassEventCopyR = 115;
	ThePassEventCopyA = 116;
	TheBuyEventCopyExtraTimesR = 117;
	TheBuyEventCopyExtraTimesA = 118;
	TheNotifyLimitTask = 119;
	TheNotifyLimitTaskExpire = 120;
	TheSyncStartLimitTask = 121;
	TheSyncFailedLimitTask = 122;
	TheFinishLimitTaskR = 123;
	TheFinishLimitTaskA = 124;
	TheNotifyRandomAward = 125;
	TheRecieveRandomAwardR = 126;
	TheRecieveRandomAwardA = 127;
	TheNotifyRandomAwardExpire = 128;
	TheSyncRandomAwardAD = 129;
	TheStartPVPBattleR = 130;
	TheStartPVPBattleA = 131;
	TheEndPVPBattleR = 132;
	TheEndPVPBattleA = 133;
	TheGetPVPBattleInfoR = 134;
	TheGetPVPBattleInfoA = 135;
	TheSyncPVPBattleRecord = 136;
	TheGetBattleRecordR = 137;
	TheGetBattleRecordA = 138;
	TheRefreshPVPBattleOppoR = 139;
	TheRefreshPVPBattleOppoA = 140;
	TheBuyPVPTicketR = 141;
	TheBuyPVPTicketA = 142;
	TheStartChallengeCopyR = 143;
	TheStartChallengeCopyA = 144;
	TheEndChallengeCopyR = 145;
	TheEndChallengeCopyA = 146;
	TheBuyShopGoodsR = 147;
	TheBuyShopGoodsA = 148;
	TheRefreshShopGoodsR = 149;
	TheRefreshShopGoodsA = 150;
	TheStartHeroMissionR = 151;
	TheStartHeroMissionA = 152;
	TheCompleteHeroMissionR = 153;
	TheCompleteHeroMissionA = 154;
	TheSpeedUpHeroMissionR = 155;
	TheSpeedUpHeroMissionA = 156;
	TheRefreshHeroMissionR = 157;
	TheRefreshHeroMissionA = 158;
	TheGetNewHeroMissionR = 159;
	TheGetNewHeroMissionA = 160;
	TheSyncHeroMissionLocked = 161;
	TheGiveupHeroMissionR = 162;
	TheGiveupHeroMissionA = 163;
	TheRecieveAlchemyR = 164;
	TheRecieveAlchemyA = 165;
	TheNotifyLevelUpAward = 166;
	TheRecieveAchievementAwardR = 167;
	TheRecieveAchievementAwardA = 168;
	TheChangePlayerNameR = 169;
	TheChangePlayerNameA = 170;
	TheCampSummonR = 171;
	TheCampSummonA = 172;
	TheClassesExchangeR = 173;
	TheClassesExchangeA = 174;
	TheClassesExchangeConfirmR = 175;
	TheClassesExchangeConfirmA = 176;
	TheGetMailListR = 177;
	TheGetMailListA = 178;
	TheNotifyNewMail = 179;
	TheRecieveMailAttachR = 180;
	TheRecieveMailAttachA = 181;
	TheDeleteMailR = 182;
	TheDeleteMailA = 183;
	TheGetFriendListR = 184;
	TheGetFriendListA = 185;
	TheSyncSendFriendGift = 186;
	TheNotifyObtainFriendGift = 187;
	TheRecieveFriendGiftR = 188;
	TheRecieveFriendGiftA = 189;
	TheSyncRequestFriend = 190;
	TheNotifyNewFriendRequest = 191;
	TheAcceptFriendRequestR = 192;
	TheAcceptFriendRequestA = 193;
	TheNotifyNewFriend = 194;
	TheSyncDeleteAllFriendRequest = 195;
	TheSyncDeleteFriend = 196;
	TheNotifyDeleteFriend = 197;
	TheSearchFriendR = 198;
	TheSearchFriendA = 199;
	TheFriendCooperationR = 200;
	TheFriendCooperationA = 201;
	TheBuyHeroBagNumR = 202;
	TheBuyHeroBagNumA = 203;
	TheIapR = 204;
	TheIapA = 205;
	TheRecieveLoginAwardR = 206;
	TheRecieveLoginAwardA = 207;
	TheSyncHeroLocked = 208;
	TheChangeIdleCopyR = 209;
	TheChangeIdleCopyA = 210;
	TheGetOtherPlayerInfoR = 211;
	TheGetOtherPlayerInfoA = 212;
	TheGetAdvertisementAwardR = 213;
	TheGetAdvertisementAwardA = 214;
	TheNotifyPlayerDailyUpdate = 215;
	TheTableCheckR = 216;
	TheTableCheckA = 217;
	TheTableUpdateR = 218;
	TheTableUpdateA = 219;
	TheAccountLoginR = 220;
	TheAccountLoginA = 221;
	TheAccountBindR = 222;
	TheAccountBindA = 223;
	TheGetRookieAwardR = 224;
	TheGetRookieAwardA = 225;
	TheGetRookieLoginAwardR = 226;
	TheGetRookieLoginAwardA = 227;
	TheFinishRookieQuestR = 228;
	TheFinishRookieQuestA = 229;
	TheGetRookieQuestAwardR = 230;
	TheGetRookieQuestAwardA = 231;
	ThePVPReplay = 232;
	ThePVPPlayerInfo = 233;
	TheActionInfo = 234;
	TheFrameActions = 235;
	ThePvpReplayAttackNomal = 236;
	ThePvpReplayParticle = 237;
	ThePVPReplayHeroHpInfo = 238;
	ThePVPReplayHeroEnergyInfo = 239;
	ThePVPReplayTextInfo = 240;
	ThePVPReplayHeroAnimatorInfo = 241;
	ThePVPReplayHeroAgentInfo = 242;
	ThePvpReplayTeleport = 243;
	ThePvpReplaySkill = 244;
	ThePVPReplayResult = 245;
	ThePvpReplayChangeSkin = 246;
	TheNotifyCheat = 247;
	TheNotifyAddHero = 248;
	TheSyncGuideStep = 249;
	TheDoWheelR = 250;
	TheDoWheelA = 251;
	TheRefreshWheelR = 252;
	TheRefreshWheelA = 253;
	TheNotifyWheelAutoRefresh = 254;
	TheBuyNormalChipR = 255;
	TheBuyNormalChipA = 256;
	TheNotifyIapPackActivation = 257;
	TheSyncAd = 258;
	TheSyncUnlockedFunctionKnown = 259;
	TheSyncAutoSkillState = 260;
	TheNotifyAlchemyRefresh = 261;
	TheCheckBattleUnit = 262;
	TheCheckBattlePVEInfo = 263;
	TheActivityQuestInfo = 264;
	TheActivityUnit = 265;
	TheActivityInfo = 266;
	TheGetActivityInfoR = 267;
	TheGetActivityInfoA = 268;
	TheNotifyActivityUpdate = 269;
	TheFinishActivityQuestR = 270;
	TheFinishActivityQuestA = 271;
	TheBuyActivitySellR = 272;
	TheBuyActivitySellA = 273;
	TheHeroAwakenR = 274;
	TheHeroAwakenA = 275;
	TheGetPVPRankingR = 276;
	TheGetPVPRankingA = 277;
	TheNotifyAddObject = 278;
	TheSyncCopyBossLose = 279;
	TheNotifyResetIapTimes = 280;
	TheBindFacebookR = 281;
	TheBindFacebookA = 282;
	TheGainFreeVrmbR = 283;
	TheGainFreeVrmbA = 284;
	TheSyncChat = 285;
	TheNotifyChat = 286;
	TheSyncAddBlockChatList = 287;
	TheSyncRemoveBlockChatList = 288;
	TheGetCacheChatListR = 289;
	TheGetCacheChatListA = 290;
	TheSyncHeroUpgrade = 291;
	TheChangePortraitR = 292;
	TheChangePortraitA = 293;
	ThePlayerBriefInfo = 294;
	TheDeviceLoginNewR = 295;
	TheDeviceLoginNewA = 296;
	TheAccountLoginNewR = 297;
	TheAccountLoginNewA = 298;
	TheAccountBindNewR = 299;
	TheAccountBindNewA = 300;
	TheChangeServerR = 301;
	TheChangeServerA = 302;
	TheReceiveCopyExtraAwardR = 303;
	TheReceiveCopyExtraAwardA = 304;
	TheReceiveChallengeExtraAwardR = 305;
	TheReceiveChallengeExtraAwardA = 306;
	TheReceiveRookieCheckInR = 307;
	TheReceiveRookieCheckInA = 308;
	TheIapLTR = 309;
	TheIapLTA = 310;
	TheIapLTOKR = 311;
	TheHeroResetR = 312;
	TheHeroResetA = 313;
	TheRankCopyPlayer = 314;
	TheRankChallengePlayer = 315;
	TheRankFightingPlayer = 316;
	TheRankProgressInfo = 317;
	TheGetCopyRankingR = 318;
	TheGetCopyRankingA = 319;
	TheGetChallengeRankingR = 320;
	TheGetChallengeRankingA = 321;
	TheGetFightingRankingR = 322;
	TheGetFightingRankingA = 323;
	TheGetTotalRankingR = 324;
	TheGetTotalRankingA = 325;
	TheRecieveRankingAwardR = 326;
	TheRecieveRankingAwardA = 327;
	TheNotifyShopAutoRefresh = 328;
	TheSyncChangeRegion = 329;
	TheSoldierToHeroR = 330;
	TheSoldierToHeroA = 331;
	TheSyncGuideQuestFinished = 332;
	TheGetGuideQuestAwardR = 333;
	TheGetGuideQuestAwardA = 334;
	TheGMServerInfo = 335;
	TheGMDictData = 336;
	TheGMOrderData = 337;
	TheGMPlayerData = 338;
	TheGMFormation = 339;
	TheGMPlayerDataParticular = 340;
	TheGMObject = 341;
	TheGMMail = 342;
	TheGMLoginR = 343;
	TheGMLoginA = 344;
	TheGMFindPlayerR = 345;
	TheGMFindPlayerA = 346;
	TheGMFindPlayerParticularR = 347;
	TheGMFindPlayerParticularA = 348;
	TheGMOperatePlayerR = 349;
	TheGMOperatePlayerA = 350;
	TheGMFindOrderR = 351;
	TheGMFindOrderA = 352;
	TheGMRepairOrderR = 353;
	TheGMRepairOrderA = 354;
	TheGMSendMailR = 355;
	TheGMSendMailA = 356;
	TheGMLog = 357;
	TheGMGetLogsR = 358;
	TheGMGetLogsA = 359;
	TheGuildBaseInfo = 360;
	TheGuildInfo = 361;
	TheGuildChangeR = 362;
	TheGuildChangeA = 363;
	TheGuildFindR = 364;
	TheGuildFindA = 365;
	TheGuildRightR = 366;
	TheGuildRightA = 367;
	TheGuildMemberInfo = 368;
	TheGuildMemberR = 369;
	TheGuildMemberA = 370;
	TheGuildAllR = 371;
	TheGuildAllA = 372;
	TheGuildApplyA = 373;
	TheGuildApplyR = 374;
	TheGuildApplyNum = 375;
	TheGuildSelfR = 376;
	TheGuildSelf = 377;
	TheGuildMsg = 378;
	TheGuildSignR = 379;
	TheGuildSignA = 380;
	TheGuildMillR = 381;
	TheGuildMillA = 382;
	TheGuildMillBeginR = 383;
	TheGuildMillBeginA = 384;
	TheGuildMillGetR = 385;
	TheGuildMillGetA = 386;
	TheGuildMillAddR = 387;
	TheGuildMillAddA = 388;
	TheGuildRankR = 389;
	TheGuildRankA = 390;
	TheGuildNotifyInfo = 391;
	TheGuildNotify = 392;
	TheGuildBossStartR = 393;
	TheGuildBossStartA = 394;
	TheGuildBossEndR = 395;
	TheGuildBossEndA = 396;
	TheTrailHeroSelf = 397;
	TheTrailHeroRobot = 398;
	TheTrailHeroStatus = 399;
	TheTrailInfo = 400;
	TheGetTrailInfoR = 401;
	TheGetTrailInfoA = 402;
	TheStartTrailBattleR = 403;
	TheStartTrailBattleA = 404;
	TheEndTrailBattleR = 405;
	TheEndTrailBattleA = 406;
	TheGetSelectBuffListR = 407;
	TheGetSelectBuffListA = 408;
	TheSelectTrailBuffR = 409;
	TheSelectTrailBuffA = 410;
	TheGetAssistHeroListR = 411;
	TheGetAssistHeroListA = 412;
	TheSelectTrailAssistR = 413;
	TheSelectTrailAssistA = 414;
	TheGetTrailStageAwardR = 415;
	TheGetTrailStageAwardA = 416;
	TheNotifyTrailReset = 417;
	TheUseTrailItemR = 418;
	TheUseTrailItemA = 419;
	TheFastBattleAwardR = 420;
	TheFastBattleAwardA = 421;
	TheDeleteAllMailR = 422;
	TheDeleteAllMailA = 423;
	TheIapPackageRewardR = 424;
	TheIapPackageRewardA = 425;
	ThePetInfo = 426;
	ThePetUnlockR = 427;
	ThePetUnlockA = 428;
	ThePetUpgradeR = 429;
	ThePetUpgradeA = 430;
	ThePetStarUpR = 431;
	ThePetStarUpA = 432;
	ThePetSkillUpR = 433;
	ThePetSkillUpA = 434;
	TheHuntingBossInfo = 435;
	TheGetHuntingBossInfoR = 436;
	TheGetHuntingBossInfoA = 437;
	TheStartHuntingBossBattleR = 438;
	TheStartHuntingBossBattleA = 439;
	TheEndHuntingBossBattleR = 440;
	TheEndHuntingBossBattleA = 441;
	TheRankHuntingBossHure = 442;
	TheGetHuntingBossRankingR = 443;
	TheGetHuntingBossRankingA = 444;
	TheChangePlayerInfoR = 445;
	TheChangePlayerInfoA = 446;
	TheLoopQuestInfo = 447;
	TheLoopQuestInfoAll = 448;
	TheLoopQuestInfoR = 449;
	TheLoopQuestInfoA = 450;
	TheLoopQuestScoreGetR = 451;
	TheLoopQuestScoreGetA = 452;
	TheLoopQuestAwardGetR = 453;
	TheLoopQuestAwardGetA = 454;
	TheLoopQuestMoneyReset = 455;
	TheStarterPackGetR = 456;
	TheStarterPackGetA = 457;
	TheNewPlayerPayInfoR = 458;
	TheNewPlayerPayInfoA = 459;
	TheNewPlayerPayGetR = 460;
	TheNewPlayerPayGetA = 461;
	TheVIPAwardGetR = 462;
	TheVIPAwardGetA = 463;
	TheVIPPackBuyR = 464;
	TheVIPPackBuyA = 465;
	TheGetNewPetFreeR = 466;
	TheGetNewPetFreeA = 467;
	TheSyncBattleSpeed = 468;
	TheAwardDirectlyEventCopyR = 469;
	TheAwardDirectlyEventCopyA = 470;
	TheDyncLanguageR = 471;
	TheDyncLanguageA = 472;
	TheGetWeekFreeR = 473;
	TheGetWeekFreeA = 474;
	TheGetMonthFreeR = 475;
	TheGetMonthFreeA = 476;
	TheHeroStarUpMultiR = 477;
	TheHeroStarUpMultiA = 478;
	TheGetLoginPlayerR = 479;
	TheGetLoginPlayerA = 480;
	TheComposeEquipMultiR = 481;
	TheComposeEquipMultiA = 482;
	TheNotifyPVPBattleRecord = 483;
	TheGetDayFreeR = 484;
	TheGetDayFreeA = 485;
	TheSyncChangeLanguage = 486;
	TheGiftCodeAwardR = 487;
	TheGiftCodeAwardA = 488;
	TheGetHeroBookAwardR = 489;
	TheGetHeroBookAwardA = 490;
	TheUseUsableItemR = 491;
	TheUseUsableItemA = 492;
	ThePetResetR = 493;
	ThePetResetA = 494;
	TheWonderSummonHeroR = 495;
	TheWonderSummonHeroA = 496;
	TheWonderHeroSelectR = 497;
	TheWonderHeroSelectA = 498;
	TheGMGetTop50RmbR = 499;
	TheGMSearchOrder50R = 500;
	TheGmCreateNewServerR = 501;
	TheGmCreateNewServerA = 502;
	TheGmGetBanInfoR = 503;
	TheGmGetBanInfoA = 504;
	TheRoleHeroStarUpR = 505;
	TheRoleHeroStarUpA = 506;
	TheRoleHeroChangeArmorR = 507;
	TheRoleHeroChangeArmorA = 508;
	TheRoleHeroArmorLevelUpR = 509;
	TheRoleHeroArmorLevelUpA = 510;
	TheMythicalCopyInfo = 511;
	TheMythicalCopyBattleBeginR = 512;
	TheMythicalCopyBattleBeginA = 513;
	TheMythicalCopyBattleEndR = 514;
	TheMythicalCopyBattleEndA = 515;
	TheMythicalCopyGetAwardR = 516;
	TheMythicalCopyGetAwardA = 517;
	TheGetLadderInfoR = 518;
	TheGetLadderInfoA = 519;
	TheGetLadderRank50R = 520;
	TheGetLadderRank50A = 521;
	TheStartLadderBattleR = 522;
	TheStartLadderBattleA = 523;
	TheEndLadderBattleR = 524;
	TheEndLadderBattleA = 525;
	TheSyncLadderBattleRecord = 526;
	TheGetLadderBattleRecordR = 527;
	TheGetLadderBattleRecordA = 528;
	TheRefreshLadderBattleOppoR = 529;
	TheRefreshLadderBattleOppoA = 530;
	TheGetLadderAchievementsR = 531;
	TheGetLadderAchievementsA = 532;
	TheIapDayAwardGetR = 533;
	TheIapDayAwardGetA = 534;
	TheSetCollegeHeroR = 535;
	TheSetCollegeHeroA = 536;
	TheOpenCollegeBlockR = 537;
	TheOpenCollegeBlockA = 538;
	TheGetActivityAccumulationAwardR = 539;
	TheGetActivityAccumulationAwardA = 540;
	TheGmGetGiftCodeR = 541;
	TheGmGetGiftCodeA = 542;
	TheGmNotice = 543;
	TheGmSetNoticeR = 544;
	TheGmSetNoticeA = 545;
	TheNotifyPlayerWeeklyUpdate = 546;
	TheNotifyPlayerMonthlyUpdate = 547;
	TheSyncDailyRedPoint = 548;
	TheSyncIsNoNoticeBoard = 549;
	TheNotifyNewNotice = 550;
	TheSyncIsAutoDecompose = 551;
	TheGetAccumulatedCheckInAwardR = 552;
	TheGetAccumulatedCheckInAwardA = 553;
	TheHeroIdList = 554;
	TheStarterSummonTenInfo = 555;
	TheStarterSummonTenR = 556;
	TheStarterSummonTenA = 557;
	TheGetStarterSummonTenAwardR = 558;
	TheGetStarterSummonTenAwardA = 559;
	TheLoopQuest2InfoAll = 560;
	TheLoopQuest2AwardGetR = 561;
	TheLoopQuest2AwardGetA = 562;
	TheLoopQuest2MoneyReset = 563;
	TheResourceUpdateZipCheckR = 564;
	TheResourceUpdateZipCheckA = 565;
	TheSyncIsHeroDecomposePrompt = 566;
	TheHeroBookUnit = 567;
	TheHeroBookActiveR = 568;
	TheHeroBookActiveA = 569;
	TheHeroBookLevelUpR = 570;
	TheHeroBookLevelUpA = 571;
	TheTitleUnit = 572;
	TheSyncChangeShowPortrait = 573;
	TheSyncChangeShowFrame = 574;
	TheSyncChangeShowTitle = 575;
	TheSyncKnowNewPortrait = 576;
	TheSyncKnowNewFrame = 577;
	TheSyncKnowNewTitle = 578;
	TheActivityRankScore = 579;
	TheGetActivityRankingR = 580;
	TheGetActivityRankingA = 581;
	TheDailyRechargeInfo = 582;
	TheGetDailyRechargeAwardR = 583;
	TheGetDailyRechargeAwardA = 584;
	TheTechnologyLevelUpR = 585;
	TheTechnologyLevelUpA = 586;
	TheTechnologyResetR = 587;
	TheTechnologyResetA = 588;
	ThePropertyMap = 589;
	TheGetRookieQuestScoreAwardR = 590;
	TheGetRookieQuestScoreAwardA = 591;
	TheGuildMonsterPInfo = 592;
	TheGuildMonsterGInfo = 593;
	TheGuildMonsterBoss = 594;
	TheGuildMonsterContributionR = 595;
	TheGuildMonsterContributionA = 596;
	TheGuildMonsterRankBase = 597;
	TheGuildMonsterContributionRankR = 598;
	TheGuildMonsterContributionRankA = 599;
	TheGuildMonsterBeginR = 600;
	TheGuildMonsterBeginA = 601;
	TheGuildMonsterBattleBeginR = 602;
	TheGuildMonsterBattleBeginA = 603;
	TheGuildMonsterBattleR = 604;
	TheGuildMonsterBattleA = 605;
	TheGuildMonsterBattleRankR = 606;
	TheGuildMonsterBattleRankA = 607;
	TheGuildMonsterBuffR = 608;
	TheGuildMonsterBuff = 609;
	TheGuildMonsterBuffA = 610;
	TheGuildMonsterAwardR = 611;
	TheGuildMonsterAwardA = 612;
	TheChallengeCopyDirectlyR = 613;
	TheChallengeCopyDirectlyA = 614;
	TheSyncIsJumpBattle = 615;
	ThePVPBattleDirectlyR = 616;
	ThePVPBattleDirectlyA = 617;
	TheAcceptFriendRequestAllR = 618;
	TheAcceptFriendRequestAllA = 619;
	TheCampCopyBattleBeginR = 620;
	TheCampCopyBattleBeginA = 621;
	TheCampCopyBattleEndR = 622;
	TheCampCopyBattleEndA = 623;
	TheGuildMonsterBattleDirectlyR = 624;
	TheGuildMonsterBattleDirectlyA = 625;
	TheGmTempR4 = 626;
	TheGmTempA4 = 627;
	TheGmTempR5 = 628;
	TheGmTempA5 = 629;
	TheGmTempR6 = 630;
	TheGmTempA6 = 631;
	TheGmTempR7 = 632;
	TheGmTempA7 = 633;
	TheGmTempR8 = 634;
	TheGmTempA8 = 635;
	TheGmTempR9 = 636;
	TheGmTempA9 = 637;
	TheCreatePVPBattleR = 638;
	TheCreatePVPBattleA = 639;
	TheRegisterBattleServerR = 640;
	TheRegisterBattleServerA = 641;
	TheTestBattleR = 642;
	TheTestBattleA = 643;
	TheBattlePlayerInfo = 644;
	TheBattleStatisticUnit = 645;
	TheCreatePVEBattleR = 646;
	TheCreatePVEBattleA = 647;
	ThebattleTempR05 = 648;
	ThebattleTempA05 = 649;
	ThebattleTempR06 = 650;
	ThebattleTempA06 = 651;
	ThebattleTempR07 = 652;
	ThebattleTempA07 = 653;
	ThebattleTempR08 = 654;
	ThebattleTempA08 = 655;
	ThebattleTempR09 = 656;
	ThebattleTempA09 = 657;
	TheReserveMessage343 = 658;
	TheReserveMessage342 = 659;
	TheReserveMessage341 = 660;
	TheReserveMessage340 = 661;
	TheReserveMessage339 = 662;
	TheReserveMessage338 = 663;
	TheReserveMessage337 = 664;
	TheReserveMessage336 = 665;
	TheReserveMessage335 = 666;
	TheReserveMessage334 = 667;
	TheReserveMessage333 = 668;
	TheReserveMessage332 = 669;
	TheReserveMessage331 = 670;
	TheReserveMessage330 = 671;
	TheReserveMessage329 = 672;
	TheReserveMessage328 = 673;
	TheReserveMessage327 = 674;
	TheReserveMessage326 = 675;
	TheReserveMessage325 = 676;
	TheReserveMessage324 = 677;
	TheReserveMessage323 = 678;
	TheReserveMessage322 = 679;
	TheReserveMessage321 = 680;
	TheReserveMessage320 = 681;
	TheReserveMessage319 = 682;
	TheReserveMessage318 = 683;
	TheReserveMessage317 = 684;
	TheReserveMessage316 = 685;
	TheReserveMessage315 = 686;
	TheReserveMessage314 = 687;
	TheReserveMessage313 = 688;
	TheReserveMessage312 = 689;
	TheReserveMessage311 = 690;
	TheReserveMessage310 = 691;
	TheReserveMessage309 = 692;
	TheReserveMessage308 = 693;
	TheReserveMessage307 = 694;
	TheReserveMessage306 = 695;
	TheReserveMessage305 = 696;
	TheReserveMessage304 = 697;
	TheReserveMessage303 = 698;
	TheReserveMessage302 = 699;
	TheReserveMessage301 = 700;
	TheReserveMessage300 = 701;
	TheReserveMessage299 = 702;
	TheReserveMessage298 = 703;
	TheReserveMessage297 = 704;
	TheReserveMessage296 = 705;
	TheReserveMessage295 = 706;
	TheReserveMessage294 = 707;
	TheReserveMessage293 = 708;
	TheReserveMessage292 = 709;
	TheReserveMessage291 = 710;
	TheReserveMessage290 = 711;
	TheReserveMessage289 = 712;
	TheReserveMessage288 = 713;
	TheReserveMessage287 = 714;
	TheReserveMessage286 = 715;
	TheReserveMessage285 = 716;
	TheReserveMessage284 = 717;
	TheReserveMessage283 = 718;
	TheReserveMessage282 = 719;
	TheReserveMessage281 = 720;
	TheReserveMessage280 = 721;
	TheReserveMessage279 = 722;
	TheReserveMessage278 = 723;
	TheReserveMessage277 = 724;
	TheReserveMessage276 = 725;
	TheReserveMessage275 = 726;
	TheReserveMessage274 = 727;
	TheReserveMessage273 = 728;
	TheReserveMessage272 = 729;
	TheReserveMessage271 = 730;
	TheReserveMessage270 = 731;
	TheReserveMessage269 = 732;
	TheReserveMessage268 = 733;
	TheReserveMessage267 = 734;
	TheReserveMessage266 = 735;
	TheReserveMessage265 = 736;
	TheReserveMessage264 = 737;
	TheReserveMessage263 = 738;
	TheReserveMessage262 = 739;
	TheReserveMessage261 = 740;
	TheReserveMessage260 = 741;
	TheReserveMessage259 = 742;
	TheReserveMessage258 = 743;
	TheReserveMessage257 = 744;
	TheReserveMessage256 = 745;
	TheReserveMessage255 = 746;
	TheReserveMessage254 = 747;
	TheReserveMessage253 = 748;
	TheReserveMessage252 = 749;
	TheReserveMessage251 = 750;
	TheReserveMessage250 = 751;
	TheReserveMessage249 = 752;
	TheReserveMessage248 = 753;
	TheReserveMessage247 = 754;
	TheReserveMessage246 = 755;
	TheReserveMessage245 = 756;
	TheReserveMessage244 = 757;
	TheReserveMessage243 = 758;
	TheReserveMessage242 = 759;
	TheReserveMessage241 = 760;
	TheReserveMessage240 = 761;
	TheReserveMessage239 = 762;
	TheReserveMessage238 = 763;
	TheReserveMessage237 = 764;
	TheReserveMessage236 = 765;
	TheReserveMessage235 = 766;
	TheReserveMessage234 = 767;
	TheReserveMessage233 = 768;
	TheReserveMessage232 = 769;
	TheReserveMessage231 = 770;
	TheReserveMessage230 = 771;
	TheReserveMessage229 = 772;
	TheReserveMessage228 = 773;
	TheReserveMessage227 = 774;
	TheReserveMessage226 = 775;
	TheReserveMessage225 = 776;
	TheReserveMessage224 = 777;
	TheReserveMessage223 = 778;
	TheReserveMessage222 = 779;
	TheReserveMessage221 = 780;
	TheReserveMessage220 = 781;
	TheReserveMessage219 = 782;
	TheReserveMessage218 = 783;
	TheReserveMessage217 = 784;
	TheReserveMessage216 = 785;
	TheReserveMessage215 = 786;
	TheReserveMessage214 = 787;
	TheReserveMessage213 = 788;
	TheReserveMessage212 = 789;
	TheReserveMessage211 = 790;
	TheReserveMessage210 = 791;
	TheReserveMessage209 = 792;
	TheReserveMessage208 = 793;
	TheReserveMessage207 = 794;
	TheReserveMessage206 = 795;
	TheReserveMessage205 = 796;
	TheReserveMessage204 = 797;
	TheReserveMessage203 = 798;
	TheReserveMessage202 = 799;
	TheReserveMessage201 = 800;
	TheReserveMessage200 = 801;
	TheReserveMessage199 = 802;
	TheReserveMessage198 = 803;
	TheReserveMessage197 = 804;
	TheReserveMessage196 = 805;
	TheReserveMessage195 = 806;
	TheReserveMessage194 = 807;
	TheReserveMessage193 = 808;
	TheReserveMessage192 = 809;
	TheReserveMessage191 = 810;
	TheReserveMessage190 = 811;
	TheReserveMessage189 = 812;
	TheReserveMessage188 = 813;
	TheReserveMessage187 = 814;
	TheReserveMessage186 = 815;
	TheReserveMessage185 = 816;
	TheReserveMessage184 = 817;
	TheReserveMessage183 = 818;
	TheReserveMessage182 = 819;
	TheReserveMessage181 = 820;
	TheReserveMessage180 = 821;
	TheReserveMessage179 = 822;
	TheReserveMessage178 = 823;
	TheReserveMessage177 = 824;
	TheReserveMessage176 = 825;
	TheReserveMessage175 = 826;
	TheReserveMessage174 = 827;
	TheReserveMessage173 = 828;
	TheReserveMessage172 = 829;
	TheReserveMessage171 = 830;
	TheReserveMessage170 = 831;
	TheReserveMessage169 = 832;
	TheReserveMessage168 = 833;
	TheReserveMessage167 = 834;
	TheReserveMessage166 = 835;
	TheReserveMessage165 = 836;
	TheReserveMessage164 = 837;
	TheReserveMessage163 = 838;
	TheReserveMessage162 = 839;
	TheReserveMessage161 = 840;
	TheReserveMessage160 = 841;
	TheReserveMessage159 = 842;
	TheReserveMessage158 = 843;
	TheReserveMessage157 = 844;
	TheReserveMessage156 = 845;
	TheReserveMessage155 = 846;
	TheReserveMessage154 = 847;
	TheReserveMessage153 = 848;
	TheReserveMessage152 = 849;
	TheReserveMessage151 = 850;
	TheReserveMessage150 = 851;
	TheReserveMessage149 = 852;
	TheReserveMessage148 = 853;
	TheReserveMessage147 = 854;
	TheReserveMessage146 = 855;
	TheReserveMessage145 = 856;
	TheReserveMessage144 = 857;
	TheReserveMessage143 = 858;
	TheReserveMessage142 = 859;
	TheReserveMessage141 = 860;
	TheReserveMessage140 = 861;
	TheReserveMessage139 = 862;
	TheReserveMessage138 = 863;
	TheReserveMessage137 = 864;
	TheReserveMessage136 = 865;
	TheReserveMessage135 = 866;
	TheReserveMessage134 = 867;
	TheReserveMessage133 = 868;
	TheReserveMessage132 = 869;
	TheReserveMessage131 = 870;
	TheReserveMessage130 = 871;
	TheReserveMessage129 = 872;
	TheReserveMessage128 = 873;
	TheReserveMessage127 = 874;
	TheReserveMessage126 = 875;
	TheReserveMessage125 = 876;
	TheReserveMessage124 = 877;
	TheReserveMessage123 = 878;
	TheReserveMessage122 = 879;
	TheReserveMessage121 = 880;
	TheReserveMessage120 = 881;
	TheReserveMessage119 = 882;
	TheReserveMessage118 = 883;
	TheReserveMessage117 = 884;
	TheReserveMessage116 = 885;
	TheReserveMessage115 = 886;
	TheReserveMessage114 = 887;
	TheReserveMessage113 = 888;
	TheReserveMessage112 = 889;
	TheReserveMessage111 = 890;
	TheReserveMessage110 = 891;
	TheReserveMessage109 = 892;
	TheReserveMessage108 = 893;
	TheReserveMessage107 = 894;
	TheReserveMessage106 = 895;
	TheReserveMessage105 = 896;
	TheReserveMessage104 = 897;
	TheReserveMessage103 = 898;
	TheReserveMessage102 = 899;
	TheReserveMessage101 = 900;
	TheReserveMessage100 = 901;
	TheReserveMessage99 = 902;
	TheReserveMessage98 = 903;
	TheReserveMessage97 = 904;
	TheReserveMessage96 = 905;
	TheReserveMessage95 = 906;
	TheReserveMessage94 = 907;
	TheReserveMessage93 = 908;
	TheReserveMessage92 = 909;
	TheReserveMessage91 = 910;
	TheReserveMessage90 = 911;
	TheReserveMessage89 = 912;
	TheReserveMessage88 = 913;
	TheReserveMessage87 = 914;
	TheReserveMessage86 = 915;
	TheReserveMessage85 = 916;
	TheReserveMessage84 = 917;
	TheReserveMessage83 = 918;
	TheReserveMessage82 = 919;
	TheReserveMessage81 = 920;
	TheReserveMessage80 = 921;
	TheReserveMessage79 = 922;
	TheReserveMessage78 = 923;
	TheReserveMessage77 = 924;
	TheReserveMessage76 = 925;
	TheReserveMessage75 = 926;
	TheReserveMessage74 = 927;
	TheReserveMessage73 = 928;
	TheReserveMessage72 = 929;
	TheReserveMessage71 = 930;
	TheReserveMessage70 = 931;
	TheReserveMessage69 = 932;
	TheReserveMessage68 = 933;
	TheReserveMessage67 = 934;
	TheReserveMessage66 = 935;
	TheReserveMessage65 = 936;
	TheReserveMessage64 = 937;
	TheReserveMessage63 = 938;
	TheReserveMessage62 = 939;
	TheReserveMessage61 = 940;
	TheReserveMessage60 = 941;
	TheReserveMessage59 = 942;
	TheReserveMessage58 = 943;
	TheReserveMessage57 = 944;
	TheReserveMessage56 = 945;
	TheReserveMessage55 = 946;
	TheReserveMessage54 = 947;
	TheReserveMessage53 = 948;
	TheReserveMessage52 = 949;
	TheReserveMessage51 = 950;
	TheReserveMessage50 = 951;
	TheReserveMessage49 = 952;
	TheReserveMessage48 = 953;
	TheReserveMessage47 = 954;
	TheReserveMessage46 = 955;
	TheReserveMessage45 = 956;
	TheReserveMessage44 = 957;
	TheReserveMessage43 = 958;
	TheReserveMessage42 = 959;
	TheReserveMessage41 = 960;
	TheReserveMessage40 = 961;
	TheReserveMessage39 = 962;
	TheReserveMessage38 = 963;
	TheReserveMessage37 = 964;
	TheReserveMessage36 = 965;
	TheReserveMessage35 = 966;
	TheReserveMessage34 = 967;
	TheReserveMessage33 = 968;
	TheReserveMessage32 = 969;
	TheReserveMessage31 = 970;
	TheReserveMessage30 = 971;
	TheReserveMessage29 = 972;
	TheReserveMessage28 = 973;
	TheReserveMessage27 = 974;
	TheReserveMessage26 = 975;
	TheReserveMessage25 = 976;
	TheReserveMessage24 = 977;
	TheReserveMessage23 = 978;
	TheReserveMessage22 = 979;
	TheReserveMessage21 = 980;
	TheReserveMessage20 = 981;
	TheReserveMessage19 = 982;
	TheReserveMessage18 = 983;
	TheReserveMessage17 = 984;
	TheReserveMessage16 = 985;
	TheReserveMessage15 = 986;
	TheReserveMessage14 = 987;
	TheReserveMessage13 = 988;
	TheReserveMessage12 = 989;
	TheReserveMessage11 = 990;
	TheReserveMessage10 = 991;
	TheReserveMessage9 = 992;
	TheReserveMessage8 = 993;
	TheReserveMessage7 = 994;
	TheReserveMessage6 = 995;
	TheReserveMessage5 = 996;
	TheReserveMessage4 = 997;
	TheReserveMessage3 = 998;
	TheReserveMessage2 = 999;
	TheReserveMessage1 = 1000;
	TheSvMsgSendPackMessageR = 1001;
	TheSvMsgSendPackMessageA = 1002;
	TheSvMsgWaitIndexMessageR = 1003;
	TheSvMsgWaitIndexMessageA = 1004;
	TheSvMsgRegisterToOtherServerR = 1005;
	TheSvMsgRegisterToOtherServerA = 1006;
	TheServerInfo = 1007;
	TheSvDownAskForConnAgent = 1008;
	TheSvMsgGetLogicServerInfosR = 1009;
	TheSvMsgGetLogicServerInfosA = 1010;
	TheSvMsgGlobalLoginA = 1011;
	TheSvWmCreateNewPlayerR = 1012;
	TheSvWmCreateNewPlayerA = 1013;
	TheSvWmGetPlayerInfoR = 1014;
	TheSvWmGetPlayerInfoA = 1015;
	TheSvPlayerInfo = 1016;
	TheSvWmPlayerLoginR = 1017;
	TheSvWmPlayerLoginA = 1018;
	TheSvNtsPlayerLogout = 1019;
	TheSvWmGetPlayerServerR = 1020;
	TheSvWmGetPlayerServerA = 1021;
	TheSvNtsAddGlobalMail = 1022;
	TheSvNtsMsgToClient = 1023;
	TheSvNtsPlayerBaseInfo = 1024;
	TheSvNtsPlayerGuildInfo = 1025;
	TheSvNtsAddGuildExp = 1026;
	TheSvFriendInfo = 1027;
	TheSvWmGetFriendInfoR = 1028;
	TheSvWmGetFriendInfoA = 1029;
	TheSvNtsSendFriendGift = 1030;
	TheSvNtsRequireFriend = 1031;
	TheSvWmAcceptFriendRequestR = 1032;
	TheSvWmAcceptFriendRequestA = 1033;
	TheSvNtsDeleteFriend = 1034;
	TheSvWmGetGMPlayerDataR = 1035;
	TheSvWmGetGMPlayerDataA = 1036;
	TheGetTemp18R = 1037;
	TheGetTemp18A = 1038;
	TheGetTemp19R = 1039;
	TheGetTemp19A = 1040;
	TheGetTemp20R = 1041;
	TheGetTemp20A = 1042;
	TheGetTemp21R = 1043;
	TheGetTemp21A = 1044;
	TheGetTemp22R = 1045;
	TheGetTemp22A = 1046;
	TheGetTemp23R = 1047;
	TheGetTemp23A = 1048;
	TheGetTemp24R = 1049;
	TheGetTemp24A = 1050;
	TheGetTemp25R = 1051;
	TheGetTemp25A = 1052;
}